name: Linux Build

on: [push, pull_request]

# At one point, "Build Anthem" and "Generate AppImage" both added the Qt directory to the path, but install-qt-action does that now.

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Download Dependencies
      run: |
           sudo apt install libxkbcommon-x11-0 -y
           sudo apt install libgl1-mesa-dev -y
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.1
    - name: Build Anthem
      run: |
           cd $GITHUB_WORKSPACE
           mkdir build && cd build
           cmake --build .. --target all
          #  qmake .. -config release
          #  make -j$(nproc)
          #  make install
    # - name: Test Anthem
    #   run: |
    #        cd $GITHUB_WORKSPACE/build/Anthem
    #        ./Anthem --test
    - name: Generate AppImage
      run: |
           cd $GITHUB_WORKSPACE/build
           export QML_SOURCES_PATHS=$GITHUB_WORKSPACE/Anthem
           wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
           wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
           chmod +x linuxdeploy*.AppImage
           ./linuxdeploy-x86_64.AppImage --appdir AppDir -e ./Anthem/Anthem -i ../actions/linux/Anthem.png -d ../actions/linux/anthem.desktop --plugin qt --output appimage
           mkdir upload
           mv ./Anthem*.AppImage ./upload
    - uses: actions/upload-artifact@master
      with:
        name: Anthem - Linux build
        path: 'build/upload'
