name: Windows Build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download Qt
      run: '. "${env:GITHUB_WORKSPACE}\actions\windows\get-qt.ps1"'
      shell: powershell
    - name: Install Qt
      run: '%GITHUB_WORKSPACE%\qt-install.exe --script .\actions\installer-noninteractive-windows.qs --verbose'
    - name: Build Anthem
      run: |
            dir D:\Qt\5.13.1\mingw73_64\bin
            D:\Qt\5.13.1\mingw73_64\bin\qtenv2.bat
            cd %GITHUB_WORKSPACE%
            qmake
            dir %GITHUB_WORKSPACE%
