name: Linux Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Download repository
      run: |
           git clone https://github.com/SecondFlight/daw-prototype.git
           cd daw-prototype
           git submodule update --init --recursive
           cd ../
    - name: Download Qt
      run: wget http://qt.mirror.constant.com/archive/qt/5.13/5.13.0/qt-opensource-linux-x64-5.13.0.run
    - name: Install Qt       
      run: |
           chmod +x ./qt-opensource-linux-x64-5.13.0.run
           ./qt-opensource-linux-x64-5.13.0.run --script ./daw-prototype/actions/installer-noninteractive-linux.qs --platform minimal
    - name: Build Anthem and make appimage
      run: |
           export PATH=$PATH:/qt/5.13.0/gcc_64/bin/
           mkdir build
           cd build 
           mkdir appdir
           qmake ../daw-prototype/Prototyping.pro
           make
           ls
